### ISSUE TITLE
Tooling updates needed to update site for 1.2

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3030]
New element types mean new requirements for `marked-schema`. With 1.2, we need tooling updates to generate our docs.

**TODO**

- [x] Run UWP test app
- [x] Generate case-insensitive schema
- [x] Host new schema along with schema versions
- [ ] Provide extensible schema
- [ ] Make the samples schema tester part of CI
