### ISSUE TITLE
Input validation & Labels Support

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3081]
# Summary

Authors need input validation, both just simple "isRequired" and more advanced than just saying that an input is required.

![ValidateOnSubmit](https://user-images.githubusercontent.com/13246069/60541698-0c484a80-9cc7-11e9-8471-32cb0d49a855.gif)

# Dev Task List Breakdown
## Input Labels Support

- [x] JS implementation | 10 days
- [x] C++ Object Model | 4 days
- [x] UWP Implementation | 4 days
- [x] Android Implementation | 4 days
- [x] iOS Implementation | 4 days
- [x] C# Object Model | 4 days
- [x] .NET implementation | 4 days
- [ ] HTML implementation | 4 days
- [ ] Bug Bash | 2 days
- [ ] Update Documentation | 2 days
- [ ] Merge from topic branch into master] | 2 days

## Input Validation Support 
- [x] JS implementation | 5 days
- [x] C++ Object Model | 6 days
- [x] UWP Implementation | 5  days
- [x] Android Implementation | 5  days
- [x] iOS Implementation | 5 days
- [x] C# Object Model | 5 days
- [x] .NET implementation | 5 days
- [ ] HTML implementation | 6 days
- [ ] Bug Bash | 7 days
- [ ] Update Documentation | 6 days

# Feature Spec including prioritized feature list & proposed schema changes
In code review at 
<https://github.com/microsoft/AdaptiveCards/pull/4190>

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/1734121

**Comment by dclaux** [comment]
My suggestions:
- `inputNecessityIndicators` (why is this an enum?) --> `showRequiredInputIndicators: true|false`
- `showInputValidationErrors`: this needs to be introduced as well as a way for a host to custom render these error messages. We've had a very long debate around this.
- `displayInputSuccessIndicators`: don't implement this feature. There is at best anecdotal evidence that we need it
- `errorMessage` --> `validationErrorMessage`

**Comment by andrewleader** [comment]
# 7/12/2019

* More spec details needed on behavior of ShowCard and which inputs it validates on
* `showInputValidationErrors` for renderers (via code) makes sense

Proposal approved

**Comment by shalinijoshi19** [comment]
Assigning to you @RebeccaAnne since you are driving this feature. thanks

**Comment by KoradaRajesh** [comment]
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "New TextBlock"
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "Input.Text",
                    "placeholder": "Placeholder text",
                    "id": "Test",
                            "validation":{
                                            "necessity":"required",
                                            "errorMessage":"New TextBlock is Required"
                                         }
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "title": "Action.Submit"
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by bodyzatva** [comment]
Can anyone tell me if this feature is available ?

**Comment by Zenulous** [comment]
This is still slated for the 1.3 milestone. In any case it is currently not available.

**Comment by nikoma** [comment]
That would be great!
