### ISSUE TITLE
[UWP] UWP has several unit test failures

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4624]
# Platform

* UWP

# Details

The following UWP tests are failing in main:

- [x]  FallbackTests (Fixed by #4627)
  - ColumnFallbackAsync (crashes test host)
- [x] ObjectModelTest (Fixed by #4626)
  - ChoiceSetInput
  - DateInput 
  - TextInput
  - ToggleInput
- [x] UnitTests
  - TestAllCards (crashes test host)
    - [x] [v1.2/Elements/AdaptiveCard.BackgroundImage.DataUri.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Elements/AdaptiveCard.BackgroundImage.DataUri.json). Fixed by #4652
    - [x] [v1.2/Elements/Column.Fallback.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Elements/Column.Fallback.json). Same issue as FallbackTests failure. Fixed by #4627.
    - [x] Out of date round-trip json files causing test failures Fixed by #4645

**Comment by RebeccaAnne** [comment]
All fixes are in and confirmed that UWP tests pass now in main.
