### ISSUE TITLE
SDK package naming 

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#653]
Tracking the final v1.0 names of the SDKs. 

# Implementation status
- [ ] TypeScript
- [ ] UWP
- [x] WPF
- [x] iOS
- [x] Android
- [x] .NET
- [ ] Documentation

## TODO

- [x] Recommend we drop the microsoft prefix 

- [X]  Figure out the best way to publish the Xamarin nugets. If it makes sense and we can include all the libs into a single package then a dev could just `nuget install AdaptiveCards`. Need to think more on if this makes sense.

- [x] Register package repo accounts at each repo and set that account as the package owner

SDK | Repository | Package name | Package spec
---|---|---|---
.NET Model | NuGet | `AdaptiveCards` | TODO
.NET HTML | NuGet | `AdaptiveCards.Rendering.Html` | TODO
.NET WPF | NuGet | `AdaptiveCards.Rendering.Wpf` | TODO
UWP | NuGet | `AdaptiveCards.Rendering.Uwp` | TODO
Xamarin iOS/Android | NuGet | `AdaptiveCards.Rendering.Xamarin` | TODO
.NET Xamarin Forms | NuGet | `AdaptiveCards.Rendering.Xamarin.Forms` | TODO
HTML Client | npm | `adaptivecards` | [Spec](https://github.com/Microsoft/AdaptiveCards/blob/master/source/html/renderer/package.json)
ReactNative | npm | `adaptivecards-react-native` | TODO
Android | Maven Central | `adaptivecards-android-[PLATFORM]` | TODO
iOS | CocoaPods | `AdaptiveCards` | TODO

**Comment by matthidinger** [comment]
@dclaux @tomlm @danmarshall this all look ok to you?

@josephwoo can you confirm with our iOS friend that this seems for for CocoaPods? If we make a watchOS renderer in the future would that be a separate package?

**Comment by dclaux** [comment]
Looks good to me.

**Comment by nesalang** [comment]
we can use AdaptiveCards as iOS package name for all platforms.
platforms are specified in podspec file.
https://guides.cocoapods.org/syntax/podspec.html#platform

**Comment by danmarshall** [comment]
👍

**Comment by matthidinger** [comment]
hey @riarenas can we make this change for UWP?
