### ISSUE TITLE
Automate Scenario Cards

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6539]
This issue tracks automation for the cards currently under v1.*\scenarios.

- [ ] Automated testing for scenario cards for JavaScript
- [ ] Automated testing for scenario cards for Xaml
- [ ] Automated testing for scenario cards for Android
- [ ] Automated testing for scenario cards for iOS
