### ISSUE TITLE
Automate RTL Tests

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6542]
This issue tracks adding automated testing for RTL. Currently existing samples:
  - v1.5\Elements\AdaptiveCard.Rtl.json
  - v1.5\Elements\Column.Rtl.json
  - v1.5\Elements\Container.Rtl.json
  - v1.5\Test\AdaptiveCard.Rtl.False.json
  - v1.5\Test\AdaptiveCard.Rtl.True.json
  - v1.5\Test\AdaptiveCard.Rtl.unset.json
  - v1.5\Test\RtlTestCard.json

Platforms
- [ ] Automated RTL tests for JavaScript
- [ ] Automated RTL tests for Xaml
- [ ] Automated RTL tests for Android
- [ ] Automated RTL tests for iOS
