### ISSUE TITLE
Automate Action Overflow Tests

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6571]
This issue tracks adding automated testing for Action Overflow. Currently existing samples:

  - v1.5\Elements\Action.Execute.Mode.json
  - v1.5\Elements\Action.OpenUrl.Mode.json
  - v1.5\Elements\Action.ShowCard.Mode.json
  - v1.5\Elements\Action.Submit.Mode.json
  - v1.5\Test\ActionModeTestCard.json

Platforms
- [ ] Automated Action Overflowtests for JavaScript
- [ ] Automated Action Overflowtests for Xaml
- [ ] Automated Action Overflowtests for Android
- [ ] Automated Action Overflowtests for iOS
