### ISSUE TITLE
Automate Tables Tests

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6573]
This issue tracks adding automated testing for Tables. Currently existing samples:
  - v1.5\Elements\Table.FirstRowAsHeaders.json
  - v1.5\Elements\Table.GridStyle.json
  - v1.5\Elements\Table.HorizontalCellContentAlignment.json
  - v1.5\Elements\Table.json
  - v1.5\Elements\Table.ShowGridLines.json
  - v1.5\Elements\Table.VerticalCellContentAlignment.json
  - v1.5\Test\TableImpliedType.json

Platforms
- [ ] Automated Table tests for JavaScript
- [ ] Automated Table tests for Xaml
- [ ] Automated Table tests for Android
- [ ] Automated Table tests for iOS
