### ISSUE TITLE
Automate Static Filtered Choice Set Tests

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6574]
This issue tracks adding automated testing for Static Filtered Choice Sets. Currently existing samples:

  - v1.5\Test\Input.ChoiceSet.FilteredStyle.TestCard.json
  - v1.5\Elements\Input.ChoiceSet.Filtered.json

Platforms
- [ ] Automated Static Filtered Choice Set tests for JavaScript
- [ ] Automated Static Filtered Choice Set tests for Xaml
- [ ] Automated Static Filtered Choice Set tests for Android
- [ ] Automated Static Filtered Choice Set tests for iOS
