### ISSUE TITLE
Automate Password Tests

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6575]
This issue tracks adding automated testing for Password boxes. Currently existing samples:
  - v1.5\Elements\Input.Text.PasswordStyle.json
  - v1.0\Elements\Input.Text.Style.json
  - v1.5\Test\Input.Text.Password.IgnoresMultiline.json

Platforms
- [ ] Automated password box tests for JavaScript
- [ ] Automated password box L tests for Xaml
- [ ] Automated password box tests for Android
- [ ] Automated password box tests for iOS
