### ISSUE TITLE
[All] Updates to release pipelines to support SBOM

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#6819]
# Description

We need to review our release pipelines across all publicly shipping platforms to make sure that we're compliant with new requirements in support of President Biden's [Executive Order](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/). 

In particular, we need to make sure we're fulfilling requirements outlined [here](https://aka.ms/eorequirements). Most of the difficult parts should already be wrapped up in PackageES tasks we can use --  we just need to wire everything up and make sure we're following SDL guidance.

## Reference
* [1ES SBOM task](https://www.1eswiki.com/wiki/ADO_sbom_Generator)
* [PackageES Security and Compliance task](https://www.osgwiki.com/wiki/Package_ES_Security_and_Compliance)

# Tasks

## UWP
- [ ] [UWP] Add SBOM task to release pipelines
- [ ] [UWP] Configure PackageES Security and Compliance task in CI or daily builds

## .NET Templating
- [ ] [Templating] Add SBOM task to release pipelines
- [ ] [Templating] Configure PackageES Security and Compliance task in CI or daily builds

## Android
- [ ] [Android] Add SBOM task to release pipelines
- [ ] [Android] Configure PackageES Security and Compliance task in CI or daily builds

## iOS
- [ ] [iOS] Add SBOM task to release pipelines
- [ ] [iOS] Configure PackageES Security and Compliance task in CI or daily builds

## NodeJS
- [ ] [NodeJS] Add SBOM task to release pipelines
- [ ] [NodeJS] Configure PackageES Security and Compliance task in CI or daily builds
