### ISSUE TITLE
Date Time formatting final spec

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#908]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>Not scheduled
<td>✔️ .NET (#959)</td>
<td></td>
</tr>
</table>

# Implementation status

- [X] TypeScript (https://github.com/Microsoft/AdaptiveCards/pull/966)
- [x] UWP
- [ ] .NET (.NET uses DateTime.Parse and is therefore not strict enough)
- [x] iOS
- [x] Android
- [ ] Documentation

# Problem

Given that ISO8601 has many accepted string formats (with and without hyphens, colons, timezone offset vs UTC, etc) it makes sense for us to clearly define a strict `DATE`/`TIME` function format and ensure all renderers adhere to it. 

This will improve reliability for card authors and prevent unfortunate situations where a developer tests on one renderer and the date shows properly, but then the same payload goes to a different renderer and the user sees a weird {{DATE(....)}} string in the middle of the card.

## Language support

Additionally, we need to know the language of the card to properly format the LONG DATE. 

If the card is sent in English, but the user's device is in Spanish then the date formatting will take the device culture and format the long date into spanish, which will look really weird in the middle of english text.

Eg., this will look super weird to a user:

Payload | Output
---|---
|`"Your order was shipped {{DATE(2017-02-13T20:46:30Z, LONG)}}"` | "Your order was shipped Lunes, 13 de Febrero, 2017" 
 

# Specification

## AdaptiveCard `lang` attribute

- [ ]  Add a `lang` attribute to `AdaptiveCard`

Consensus is to add a top-level property to AdaptiveCard to support the language. This aligns with [HTML's design](https://www.w3.org/International/tutorials/language-decl/) of `<html lang="en">`

## Date/Time parsing spec 

1. **CASE SENSITIVE** (must be all caps)
1. **NO SPACES** between the `{{`, `}}`, or parentheses
1. **STRICT [RFC 3389](https://tools.ietf.org/html/rfc3339) FORMATTING** (See examples below)
1. **MUST BE** a valid date and time
1. **ALL FAILURES MUST** display the raw string in the card. No friendly message attempted. (The goal being to make the developer immediately aware there is a problem)

### Valid formats

The only accepted format follows [RFC 3389](https://tools.ietf.org/html/rfc3339)

`YYYY "-" MM "-" DD "T" HH ":" MM ":" SS [OFFSET]`
`[OFFSET]` may be the literal "Z" for UTC, or an hour-minute offset, seen below:

`2017-02-14T06:08:00Z`
`2017-02-14T06:08:00-07:00`
`2017-02-14T06:08:00+07:00`

### Date Formatting

The `DATE` function allows an optional formatting param to tailor to output string.

1. **OPTIONAL** space allowed before LONG/SHORT/COMPACT (RegEx: `/w+`)
2. **CASE SENSITIVE** (must be all caps)
3. Any **UNKNOWN** format param should fall-back to COMPACT (to future proof the parameter)

Format | Example
---|---
COMPACT (Default) | "2/13/2017" 
SHORT | "Mon, Feb 13th, 2017"
LONG | "Monday, February 13th, 2017"

### Time Formatting

The `TIME` function does not have a formatting param and should not include the seconds. E.g., "6:01 PM" or "18:01"

# Examples

The follow examples cover the requirements above. The VALID formats should render correctly. The INVALID sections should return the date {{DATE}} / {{TIME}} string

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "lang": "en",
    "version": "1.0",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "VALID DATE / TIME FORMATS",
                    "size": "large",
                    "color": "good"
                },
                {
                    "type": "TextBlock",
                    "text": "No offset {{DATE(2017-02-14T06:08:00Z)}} {{TIME(2017-02-14T06:08:00Z)}}",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "Positive offset {{DATE(2017-02-14T06:08:00+04:00)}} {{TIME(2017-02-14T06:08:00+04:00)}}",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "Negative offset {{DATE(2017-02-14T06:08:00-07:00)}} {{TIME(2017-02-14T06:08:00-07:00)}}",
                    "wrap": true
                }
            ]
        },
        {
            "type": "Container",
            "spacing": "large",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "VALID DATE FORMAT OPTIONS",
                    "size": "large",
                    "color": "good"
                },
                {
                    "type": "TextBlock",
                    "text": "{{DATE(2017-02-14T06:08:00Z, COMPACT)}} (Default)",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "{{DATE(2017-02-14T06:08:00Z, SHORT)}}",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "{{DATE(2017-02-14T06:08:00Z, LONG)}}",
                    "wrap": true
                }
            ]
        },
        {
            "type": "Container",
            "spacing": "large",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "INVALID DATE / TIME FORMATS",
                    "size": "large",
                    "color": "attention"
                },
                {
                    "type": "TextBlock",
                    "text": "Invalid Spaces {{ DATE(2017-02-14T06:08:00Z) }} {{ TIME(2017-02-14T06:08:00Z) }}",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "Invalid Date {{DATE(2017-99-14T06:08:00Z)}} {{TIME(2017-99-14T06:08:00Z)}}",
                    "wrap": true
                },                
                {
                    "type": "TextBlock",
                    "text": "Invalid casing {{date(2017-02-14T06:08:00Z)}} {{Time(2017-02-14T06:08:00Z)}}",
                    "wrap": true
                },                                
                {
                    "type": "TextBlock",
                    "text": "Missing seconds {{DATE(2017-10-27T22:27Z)}} {{TIME(2017-10-27T22:27:00Z)}}",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "TIME doesn't allow a format param {{TIME(2017-02-14T06:08:00Z, SHORT)}}",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "{{DATE(2017-02-14T06:08:00Z, RANDOMTEXT)}}"
                }

            ]
        }
      ]
  }
```

# Auto-generated task status

- [x] .NET

**Comment by dclaux** [comment]
I favor having a lang property at the card level, but regardless of the chosen option:
- What will be the list of valid language values? Will we be using the [BCP 47](https://tools.ietf.org/html/bcp47) format?
- How do we map them to the various platforms our renderers run on? Is BCP 47 supported on all of them?
- Do we want to support fallback locales as [JavaScript does](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)?

Why only support UTC? And if we support only UTC why do we need the trailing Z? I think we should should support the full format as we currently do.

**Comment by riarenas** [comment]
What value does supporting the offsets give card authors? Most date-time libraries work by transforming any date with offset into a utc time and then converting to the local timezone. It's just as easy for a card author to go from their local time to UTC as it is for the renderers.

If we support offests, which format of offset are we going to support?
2017-02-14T06:08:00+6 
2017-02-14T06:08:00+6:30
2017-02-14T06:08:00+6:30:23

Are all valid according to the standard, but only the first one is valid for the Typescript renderer right now. If we're going to limit the offset format, I believe there's little value in having it.

**Comment by riarenas** [comment]
Additionally, the typescript renderer only accepts negative offsets, 2017-02-14T06:08:00+6 is not recognized. And 2017-02-14T06:08:00-0 is valid although the standard says that it shouldn't.

**Comment by dclaux** [comment]
Putting aside the bugs in the TypeScript renderer, which need to be fixed, the value is that this format is well known and understood. There might be scenarios that use an offset right now for all we know, and we would break them.

[ISO 3339](https://tools.ietf.org/html/rfc3339) isn't permissive as you say it is above, it is super strict:

```
date-fullyear   = 4DIGIT
   date-month      = 2DIGIT  ; 01-12
   date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on month/year
   time-hour       = 2DIGIT  ; 00-23
   time-minute     = 2DIGIT  ; 00-59
   time-second     = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second rules
   time-secfrac    = "." 1*DIGIT
   time-numoffset  = ("+" / "-") time-hour ":" time-minute
   time-offset     = "Z" / time-numoffset

   partial-time    = time-hour ":" time-minute ":" time-second [time-secfrac]
   full-date       = date-fullyear "-" date-month "-" date-mday
   full-time       = partial-time time-offset

   date-time       = full-date "T" full-time
```

I'm not saying we'd go as far as supporting the leap second rules (in JS at least the RegEx we use to do basic validation can be more permissive while the underlying platform does the heavy lifting) but I don't know why Adaptive would be the only example I know of only supporting UTC.

**Comment by riarenas** [comment]
The only reason I bring up the issues with the typescript renderer is to illustrate how a "simple" addition like offsets can lend itself to becoming confusing.

If what you are suggesting is we adopt RFC 3339 as our date format instead of ISO 8601, then all the renderers should align to the RFC's spec. The RFC however is not really a standard, and non-web developers might still face issues when trying to represent their ISO 8601 compliant dates that are invalid according to the RFC. (As an example, ISO 8601 allows times without seconds, while in the RFC only the second fractions are optional)

Seems like it's much easier to just take a small subset of what we need from the ISO standard, make it as strict as possible, and document that as what we allow in our payloads.

**Comment by riarenas** [comment]
However, if we do feel accepting the offsets is a useful thing. I believe switching to RFC 3339 is a good way to go. It's by far less flexible than our currently documented ISO 8601.

**Comment by matthidinger** [comment]
So to confirm based on 3389, here are the final valid options, correct?

`2017-02-14T06:08:00Z`
` 2017-02-14T06:08:00-07:00`
` 2017-02-14T06:08:00+07:00`

**Comment by riarenas** [comment]
But then we're neither ISO 8601 nor RFC 3389? In my opinion following 3389 would be the correct way to go, which would mean 2017-02-14T06:08:00-07 and 2017-02-14T06:08:00+07 should not be valid.

**Comment by matthidinger** [comment]
Indeed the point we are really trying to drive home is that consistency and reliability *on all platforms* should trump flexibility at this stage. We are implementing this time parsing/rending code on ~8 platforms and it's important that they all behave exactly the same. That's why we really need to nail this spec, document it well for card authors, and implement it the exact same way everywhere before we ship. 

RFC 3389 seems good. Anything else should fail. That work for everyone?

**Comment by dclaux** [comment]
Sure.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ferventmoss** [comment]
Only thing concerns me is second fractions for offset. Are we going to allow it?

**Comment by matthidinger** [comment]
@ferventmoss no, the only deviation from 3389 would be the seconds fraction, we will not allow it. I'll uddate the spec with the latest from this thread

**Comment by nesalang** [comment]
Thanks matt, stupid chrome signed me as Ferventmoss. sorry for the confusion if you had any!
One last thing, time will be represented as hh:mm pm/am, right? e.g. 11:00 AM

**Comment by matthidinger** [comment]
@nesalang yeah that sounds correct to me

**Comment by riarenas** [comment]
Is that something we can leave up to the time/date library? I noticed that when I switch my region, 10:57 AM becomes 10:57 a.m.

If not, I think hh:mm PM|AM is fine.

**Comment by nesalang** [comment]
yes, it is handled by the time library.

**Comment by matthidinger** [comment]
I've updated the spec and good/bad payload examples for testing

**Comment by dclaux** [comment]
One last thing - why impose case sensitiveness? It's only going to generate frustration and questions on support forums IMO. I'm fairly certain that all date/time parsing libraries out there are case insensitive, so implementation shouldn't be a problem. I know that being case insensitive isn't per RFC 3389, but it would just make things easier IMO.

**Comment by dclaux** [comment]
We haven't defined **whether time formatting should include seconds**. I believe it should not (there are calendaring scenarios in Outlook where including seconds just doesn't make any sense).

Thoughts?

**Comment by shalinijoshi19** [comment]
@RebeccaAnne / @paulcam206 / @nesalang / @almedina-ms / @andrewleader : do we know why this issue is still open?

**Comment by andrewleader** [comment]
It seems like .NET is [correctly strict now](https://github.com/Microsoft/AdaptiveCards/blob/f915e02a017cf2dba85e4219adbcd1e851a102bc/source/dotnet/Library/AdaptiveCards/Rendering/RendererUtilities.cs#L17), as far as I know this should be closed? Anyone else know any renderers that aren't correctly strictly parsing the DateTime?

**Comment by shalinijoshi19** [comment]
Closing this out.

**Comment by bw-kforce-ms** [comment]
The documentation states you follow RFC3339 strictly, yet the examples in section 5.8, only 1 of 5 render in the Visualizer/Designer.  You mentioned fractional seconds are not allowed, yet this is not reflected in this documentation. I had to follow the closed issue chain to find out they were not allowed.  Please update the documentation.

**Comment by andrewleader** [comment]
Thanks bw-kforce-ms for the feedback! Looks like we're indeed missing some functionality of RFC3339, like **fractional seconds** and **leap second support**. We'll either update the documentation to say this, or update the renderers to fully support RFC3339.

**Comment by FKPSC** [comment]
Fractional seconds are part of [RFC 3389](https://tools.ietf.org/html/rfc3339). They are used by default in:
- Javascript: 
```js
new Date().toISOString()
// outputs
'2025-08-22T19:23:18.773Z'
```
- PostgreSQL
```SQL
select now();

now
------------------------------
2025-08-22 21:28:00.98689+02
(1 row)
```
These are 2 among many other widely used platforms. Those values won't be displayed in any way but supporting allowing them would reduce the formatting/string manipulation overhead. It's also very trivial to add those to regex.

Could this be implemented in 1.7?
